# View system configs:

In [ ]:
!cat /etc/*release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


In [ ]:
!nvidia-smi -L

GPU 0: NVIDIA A100-SXM4-40GB (UUID: GPU-eaffa791-1061-a29c-51ec-b4b82d8ece07)


In [ ]:
!nvidia-smi -q


==============NVSMI LOG==============

Timestamp                                 : Thu Feb  2 10:01:51 2023
Driver Version                            : 510.47.03
CUDA Version                              : 11.6

Attached GPUs                             : 1
GPU 00000000:00:04.0
    Product Name                          : NVIDIA A100-SXM4-40GB
    Product Brand                         : NVIDIA
    Product Architecture                  : Ampere
    Display Mode                          : Enabled
    Display Active                        : Disabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : Disabled
        Pending                           : Disabled
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : 1324521070984
  

In [ ]:
!lscpu |grep 'Model name'

Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz


In [ ]:
!lscpu

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:                        7
CPU MHz:                         2200.204
BogoMIPS:                        4400.40
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        6 MiB
L3 cache:                        38.5 MiB
NUMA node0 CPU(s):               0-11
Vulnerabi

In [ ]:
!nvidia-smi

Wed Feb  1 08:40:49 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    29W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# pip commands:

In [ ]:
!python --version

Python 3.8.10


In [ ]:
!pip --version

pip 22.0.4 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)


In [ ]:
!pip uninstall tensorflow

Found existing installation: tensorflow 2.9.2
Uninstalling tensorflow-2.9.2:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.8/dist-packages/tensorflow-2.9.2.dist-info/*
    /usr/local/lib/python3.8/dist-packages/tensorflow/*
Proceed (Y/n)? Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/commands/uninstall.py", line 97, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/req_install.py", line 638, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  Fi

In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# imports:

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import tensorflow as tf2 #Tensorflow 2.x
tf2.compat.v1.nn.rnn_cell.LSTMCell(num_units=10,
                            state_is_tuple=True,
                            initializer= tf2.initializers.GlorotUniform()
                           ) 
import numpy as np
import datetime
import sys
import os
import csv
import pickle

Instructions for updating:
non-resource variables are not supported in the long term
<ipython-input-4-77dd65dae29b>:4: UserWarning: `tf.nn.rnn_cell.LSTMCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.layers.LSTMCell`, and will be replaced by that in Tensorflow 2.0.
  tf2.compat.v1.nn.rnn_cell.LSTMCell(num_units=10,


# GPU config:

In [ ]:
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Desired graphics card config
session_conf = tf.ConfigProto(
    allow_soft_placement=True,
    log_device_placement=False,
    gpu_options=tf.GPUOptions(allow_growth=True))


# Parametrs:

In [ ]:
np.random.seed(10)

# Data loading params
tf.flags.DEFINE_float("dev_sample_percentage", .1, "Percentage of the training data to use for validation")

# Model Hyperparameters
tf.flags.DEFINE_integer("embedding_dim", 300, "Dimensionality of character embedding (default: 128)")
tf.flags.DEFINE_string("filter_sizes", "3,4,5", "Comma-separated filter sizes (default: '3,4,5')")
tf.flags.DEFINE_integer("num_filters", 128, "Number of filters per filter size (default: 128)")
tf.flags.DEFINE_float("dropout_keep_prob", 0.5, "Dropout keep probability (default: 0.5)")
tf.flags.DEFINE_float("l2_reg_lambda", 0.5, "L2 regularization lambda (default: 0.0)")

# Training parameters
tf.flags.DEFINE_integer("batch_size", 4096, "Batch Size (default: 64)")
tf.flags.DEFINE_integer("num_epochs", 100, "Number of training epochs (default: 200)")
tf.flags.DEFINE_integer("evaluate_every", 100, "Evaluate model on dev set after this many steps (default: 100)")
tf.flags.DEFINE_integer("checkpoint_every", 100, "Save model after this many steps (default: 100)")
tf.flags.DEFINE_integer("num_checkpoints", 5, "Number of checkpoints to store (default: 5)")
# Misc Parameters
tf.flags.DEFINE_boolean("allow_soft_placement", True, "Allow device soft device placement")
tf.flags.DEFINE_boolean("log_device_placement", False, "Log placement of ops on devices")

FLAGS = tf.flags.FLAGS


In [ ]:
tf.flags.DEFINE_string('f','','')

# Connect to google drive:

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## train stylometric:

In [ ]:
!python /content/drive/MyDrive/twitter/users/train_stylometric_for_users.py

2023-02-04 19:24:24,705 : INFO : collecting all words and their counts
2023-02-04 19:24:24,705 : INFO : PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
2023-02-04 19:24:25,162 : INFO : PROGRESS: at example #10000, processed 1784539 words (3908371/s), 121423 word types, 9779 tags
2023-02-04 19:24:25,486 : INFO : collected 181291 word types and 16583 unique tags from a corpus of 16968 examples and 3050719 words
2023-02-04 19:24:25,486 : INFO : Loading a fresh vocabulary
2023-02-04 19:24:25,609 : INFO : effective_min_count=5 retains 26653 unique words (14% of original 181291, drops 154638)
2023-02-04 19:24:25,609 : INFO : effective_min_count=5 leaves 2830567 word corpus (92% of original 3050719, drops 220152)
2023-02-04 19:24:25,670 : INFO : deleting the raw counts dictionary of 181291 items
2023-02-04 19:24:25,674 : INFO : sample=0.001 downsamples 23 most-common words
2023-02-04 19:24:25,674 : INFO : downsampling leaves estimated 2436303 word corpus (86.1% of prior

## generate stylometric:

In [ ]:
!python /content/drive/MyDrive/twitter/users/generate_stylometric_for_users.py

length of vectors:  16970
length of users:  16970
vectors:  [[-0.0009744   0.00121197 -0.00039568 ...  0.00502842 -0.00065766
  -0.00619751]
 [ 0.00489702  0.001238    0.00257418 ... -0.00532112  0.00275299
  -0.00047422]
 [ 0.00101636 -0.00307163  0.00222701 ... -0.00394206 -0.00218419
   0.00140551]
 ...
 [ 0.00500952  0.00325866 -0.00131573 ... -0.00343822 -0.00323413
   0.00433683]
 [ 0.00054966  0.00026495 -0.00439403 ... -0.00506976 -0.00114843
  -0.0052082 ]
 [ 0.00423496  0.00016113  0.00267497 ... -0.00356189  0.00379445
  -0.00040208]]


## generate users veiw:

In [ ]:
!python /content/drive/MyDrive/twitter/users/generte_user_view.py

## user gcca:

In [ ]:
!python /content/drive/MyDrive/twitter/users/user_wgcca.py --input /content/drive/MyDrive/twitter_files/user_embeddings/users_view_vectors_80.csv --output /content/drive/MyDrive/twitter_files/user_embeddings/users_gcca_embeddings_80.npz --k 80 --no_of_views 1

N =  16970
Reading line: 0K
Reading line: 10K
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
Decomposed data matrix for view 0
Decomposed M_tilde / solved for G
Solved for U in view 0


# Load data:

In [ ]:
VECTOR_SIZE = 80

In [ ]:
print("loading data...")
x = pickle.load(open("/content/drive/MyDrive/twitter_files/models/main_balanced_pickle.p", "rb"))
revs, W, W2, word_idx_map, vocab, max_l = x[0], x[1], x[2], x[3], x[4], x[5]
print("data loaded!") 


loading data...
data loaded!


In [ ]:
print(max_l)

62


In [ ]:
print('loading wgcca embeddings...')
# wgcca_embeddings = np.load('/content/drive/MyDrive/twitter_files/models/users_gcca_embeddings.npz')
wgcca_embeddings = np.load('/content/drive/MyDrive/twitter_files/user_embeddings/users_gcca_embeddings_80.npz')

print('wgcca embeddings loaded')

loading wgcca embeddings...
wgcca embeddings loaded


# Code:

In [ ]:
ids = np.concatenate((np.array(["unknown"]), wgcca_embeddings['ids']), axis=0)
user_embeddings = wgcca_embeddings['G']
unknown_vector = np.random.normal(size=(1, VECTOR_SIZE))
user_embeddings = np.concatenate((unknown_vector, user_embeddings), axis=0)
user_embeddings = user_embeddings.astype(dtype='float32')


In [ ]:
print(len(wgcca_embeddings['ids']))

16970


In [ ]:
print(len(ids))

16971


In [ ]:
wgcca_dict = {}
print("ids length: ", len(ids))
for i in range(len(ids)):
    wgcca_dict[ids[i]] = int(i)

ids length:  16971


In [ ]:
x_text = []
author_text_id = []
y = []

test_x = []
test_author = []
test_y = []

In [ ]:
for i in range(len(revs)):
    if revs[i]['split'] == 1:
        x_text.append(revs[i]['text'])
        try:
            author_text_id.append(wgcca_dict['"user_id:' + str(revs[i]['author']) + '"'])
        except KeyError:
            author_text_id.append(0)
        temp_y = revs[i]['label']
        y.append(temp_y)
    else:
        test_x.append(revs[i]['text'])
        try:
            test_author.append(wgcca_dict['"user_id:' + str(revs[i]['author']) + '"'])
        except:
            test_author.append(0)
        test_y.append(revs[i]['label'])


### print:

In [ ]:
x_text
print(len(x_text))

13575


In [ ]:
x_text

['twitter show repli graham investig know taxpay fund read far enough got annoy call',
 'kikischoc graynott case miss elect member countri work much say eu countri',
 'heymolz jl obvious',
 '',
 'allisonpearson abcnew gb clever admit doctor perhap read telegraph get balanc',
 'love want world know cute squash',
 'sawerapasha captainmisbahpk yes best pick mishap amp perform role extrem well hope rest benchwarm would also get chanc',
 'ryanshead marleneflorkow realdonaldtrump bunch crap',
 'jetsnihilist would rather sam learn anoth offens latin next year stay garbag offens garbag coach staff',
 'realli though mfs mention realli tri cut base opinion',
 'lol genet ft in alway ask grab stuff groceri store random stranger good luck paint',
 'sure new compar treat versus treat ask dem candid etc compar us third world countri stori whether condemn obama harsh get cricket',
 'brianbunessan think union alway tri luck plenti strike labour past dead get buri one point',
 'act like justin own break

In [ ]:
author_text_id
print(len(author_text_id))

13575


In [ ]:
print(len(y))

13575


In [ ]:
test_x
print(len(test_x))

3395


In [ ]:
# test_author
counter = 0
for i in test_author:
  if i != 0:
    counter+=1
print(counter)

3395


In [ ]:
print(len(test_y))

3395


### code:

In [ ]:
y = np.asarray(y)
test_y = np.asarray(test_y)


In [ ]:
len(y)

13575

# Get word indices:


In [ ]:
# get word indices
x = []
for i in range(len(x_text)):
    x.append(np.asarray([word_idx_map[word] for word in x_text[i].split()]))

x_test = []
for i in range(len(test_x)):
    x_test.append(np.asarray([word_idx_map[word] for word in test_x[i].split()]))


In [ ]:
x_test

[array([22894,    84,   293,    34]),
 array([22895,  1679,  2424]),
 array([2121]),
 array([7617,  183,  149,  663,  230,   42, 1067,  433,  273]),
 array([10252,   204,  8524,  2490,  7772,   291,    83,    62,  5434,
         3257]),
 array([ 489, 1844]),
 array([22896,   311,  2474,    43]),
 array([22897,   872,   132,  8372,  5577,   135,  5344,  8757,  9736,
          798,  8818,   678,  1067,    12,   102]),
 array([3034, 1840, 9202,  155,   75,   35,  364, 7580,    8,   39, 1638,
        6188, 2084,  394,  238]),
 array([ 732,  213, 1488, 1915, 3656, 9832, 9697,  914, 1078]),
 array([22898,  7770,  9847,   931,   684,   489,   143,  7732,   684,
         3908,    51,  7963,   143,    62,   153,    22,   224]),
 array([22899,  2337,   328,   920,    11,   192,    41,  2916,   332,
          135,    20,   894,    11,   186,   192,   920,    41,  8248,
         9670,    67,   958,   458,   349]),
 array([882,  30]),
 array([   92,    61,    91,  9098,   134, 15629,  1898,  3337, 

# Padding:

In [ ]:
max_l = 80

In [ ]:
for i in range(len(x)):
    if (len(x[i]) < max_l):
        x[i] = np.append(x[i], np.zeros(max_l - len(x[i])))
    elif (len(x[i]) > max_l):
        x[i] = x[i][0:max_l]
x = np.asarray(x)

for i in range(len(x_test)):
    if (len(x_test[i]) < max_l):
        x_test[i] = np.append(x_test[i], np.zeros(max_l - len(x_test[i])))
    elif (len(x_test[i]) > max_l):
        x_test[i] = x_test[i][0:max_l]
x_test = np.asarray(x_test)

In [ ]:
y_test = test_y
author_train = np.asarray(author_text_id)
author_test = np.asarray(test_author)

In [ ]:
len(author_train)

13575

### shuffle_indices:

In [ ]:
shuffle_indices = np.random.permutation(np.arange(len(y)))
x_shuffled = x[shuffle_indices]
y_shuffled = y[shuffle_indices]
author_train_shuffled = author_train[shuffle_indices]


In [ ]:
len(shuffle_indices)

13575

FLAGS.dev_sample_percentage = .1

In [ ]:
dev_sample_index = -1 * int(FLAGS.dev_sample_percentage * float(len(y)))
x_train, x_dev = x_shuffled[:dev_sample_index], x_shuffled[dev_sample_index:]
author_train, author_dev = author_train_shuffled[:dev_sample_index], author_train_shuffled[dev_sample_index:]
y_train, y_dev = y_shuffled[:dev_sample_index], y_shuffled[dev_sample_index:]
print("Train/Dev split: {:d}/{:d}".format(len(y_train), len(y_dev)))

Train/Dev split: 12218/1357


In [ ]:
x_train = np.asarray(x_train)
x_dev = np.asarray(x_dev)
author_train = np.asarray(author_train)
author_dev = np.asarray(author_dev)
y_train = np.asarray(y_train)
y_dev = np.asarray(y_dev)
word_idx_map["@"] = 0
rev_dict = {v: k for k, v in word_idx_map.items()}

In [ ]:
rev_dict

{1: 'in',
 2: 'that',
 3: 'on',
 4: 'or',
 5: 'your',
 6: 'all',
 7: 'be',
 8: 'one',
 9: 'will',
 10: 'can',
 11: 'time',
 12: 'like',
 13: 'also',
 14: 'there',
 15: 'get',
 16: 'what',
 17: 'out',
 18: 'an',
 19: 'up',
 20: 'would',
 21: 'new',
 22: 'make',
 23: 'other',
 24: 'use',
 25: 'said',
 26: 'first',
 27: 'work',
 28: 'over',
 29: 'way',
 30: 'see',
 31: 'good',
 32: 'here',
 33: 'made',
 34: 'great',
 35: 'us',
 36: 'even',
 37: 'two',
 38: 'back',
 39: 'could',
 40: 'still',
 41: 'go',
 42: 'know',
 43: 'day',
 44: 'take',
 45: 'most',
 46: 'right',
 47: 'love',
 48: 'world',
 49: 'best',
 50: 'find',
 51: 'say',
 52: 'think',
 53: 'need',
 54: 'around',
 55: 'home',
 56: 'life',
 57: 'place',
 58: 'off',
 59: 'help',
 60: 'may',
 61: 'found',
 62: 'year',
 63: 'got',
 64: 'down',
 65: 'game',
 66: 'book',
 67: 'read',
 68: 'put',
 69: 'set',
 70: 'today',
 71: 'better',
 72: 'want',
 73: 'under',
 74: 'show',
 75: 'well',
 76: 'look',
 77: 'come',
 78: 'much',
 79: 'with

# Training:

In [ ]:

class TextCNN(object):
    """
    A CNN for text classification.
    Uses an embedding layer, followed by a convolutional, max-pooling and softmax layer.
    """

    def __init__(
            self, sequence_length, num_classes, vocab_size, word2vec_W, word_idx_map, user_embeddings,
            embedding_size, batch_size, filter_sizes, num_filters, l2_reg_lambda=0.0):

        print("num_classes: ", num_classes)
        print("sequence_length: ", sequence_length)
        print("vocab_size: ", vocab_size)
        print("batch_size: ", batch_size)
        print("filter_sizes: ", filter_sizes)
        print("num_filters: ", num_filters)
        print("embedding_size: ", embedding_size)

        # Placeholders for input, output and dropout
        self.input_x = tf.placeholder(tf.int32, [None, sequence_length], name="input_x")
        self.input_y = tf.placeholder(tf.float32, [None, num_classes], name="input_y")
        self.input_author = tf.placeholder(tf.int32, [None], name="input_author")
        self.dropout_keep_prob = tf.placeholder(tf.float32, name="dropout_keep_prob")

        # Keeping track of l2 regularization loss (optional)
        l2_loss = tf.constant(0.0)

        print("l2_loss: ", l2_loss)

        # Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
            self.W = tf.Variable(word2vec_W, name="W")
            self.user_W = tf.Variable(user_embeddings, name='user_W')
            self.embedded_chars = tf.nn.embedding_lookup(self.W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)
            self.user_embedding_vectors = tf.nn.embedding_lookup(self.user_W, self.input_author)
        # Create a convolution + maxpool layer for each filter size
        pooled_outputs = []
        for i, filter_size in enumerate(filter_sizes):
            with tf.name_scope("conv-maxpool-%s" % filter_size):
                # Convolution Layer
                filter_shape = [filter_size, embedding_size, 1, num_filters]
                W = tf.Variable(tf.truncated_normal(filter_shape, stddev=0.1), name="W")
                b = tf.Variable(tf.constant(0.1, shape=[num_filters]), name="b")
                conv = tf.nn.conv2d(
                    self.embedded_chars_expanded,
                    W,
                    strides=[1, 1, 1, 1],
                    padding="VALID",
                    name="conv")
                
                print("conv: ", conv)
                # Apply nonlinearity
                h = tf.nn.relu(tf.nn.bias_add(conv, b), name="relu")
                # Maxpooling over the outputs
                pooled = tf.nn.max_pool(
                    h,
                    ksize=[1, sequence_length - filter_size + 1, 1, 1],
                    strides=[1, 1, 1, 1],
                    padding='VALID',
                    name="pool")
                print("pooled: ", pooled)
                pooled_outputs.append(pooled)

        # Combine all the pooled features
        num_filters_total = num_filters * len(filter_sizes)
        self.h_pool = tf.concat(pooled_outputs, 3)
        self.h_pool_flat = tf.reshape(self.h_pool, [-1, num_filters_total], name="h_pool_flat")

        print("h_pool_flat: ", self.h_pool_flat)
        # Add another layer
        with tf.name_scope("last_layer"):
            C = tf.Variable(tf.random_normal([num_filters_total, VECTOR_SIZE]), name="C")
            b_prime = tf.Variable(tf.constant(0.1, shape=[VECTOR_SIZE]), name="b_prime")
            self.h_last = tf.nn.xw_plus_b(self.h_pool_flat, C, b_prime, name="h_last")

        print("h_last: ", self.h_last)
        print("user_embedding_vectors: ", self.user_embedding_vectors)

        # Add user embeddings
        with tf.name_scope("user_embedding_layer"):
            U = tf.Variable(tf.random_normal([2*VECTOR_SIZE, 400]), name="U") ### 300-->200
            b_user = tf.Variable(tf.constant(0.1, shape=[400], name='b_user'))
            self.combined_vectors = tf.concat([self.h_last, self.user_embedding_vectors], 1)
            print("combined_vectors: ", self.combined_vectors)
            self.final_vector = tf.nn.relu(tf.nn.xw_plus_b(self.combined_vectors, U, b_user), name='final_vector')

        print("final_vector: ", self.final_vector)

        # Add dropout
        with tf.name_scope("dropout"):
            self.h_drop = tf.nn.dropout(self.final_vector, self.dropout_keep_prob, name="h_drop")
        
        print("h_drop: ",self.h_drop)

        # Final (unnormalized) scores and predictions
        with tf.name_scope("output"):
            W = tf.get_variable(
                "W",
                shape=[400, num_classes],
                initializer=tf2.initializers.GlorotUniform())
                # initializer=tf.contrib.layers.xavier_initializer())
            b = tf.Variable(tf.constant(0.1, shape=[num_classes]), name="b")
            l2_loss += tf2.nn.l2_loss(W)
            l2_loss += tf.nn.l2_loss(b)
            self.scores = tf.nn.xw_plus_b(self.h_drop, W, b, name="scores")
            print(self.scores)
            self.predictions = tf.argmax(self.scores, 1, name="predictions")

        # CalculateMean cross-entropy loss
        with tf.name_scope("loss"):
            losses = tf.nn.softmax_cross_entropy_with_logits(logits=self.scores, labels=self.input_y)
            self.loss = tf.reduce_mean(losses) + l2_reg_lambda * l2_loss

        # Accuracy
        with tf.name_scope("accuracy"):
            correct_predictions = tf.equal(self.predictions, tf.argmax(self.input_y, 1))
            self.accuracy = tf.reduce_mean(tf.cast(correct_predictions, "float"), name="accuracy")

        with tf.name_scope("correct_preds"):
            self.correct_predictions = correct_predictions

        with tf.name_scope("predictions"):
            self.predictions

        with tf.name_scope("confusion_matrix"):
            self.labels = tf.argmax(self.input_y, 1, name="labels")
            self.confusion_matrix = tf.confusion_matrix(labels=self.labels, predictions=self.predictions,
                                                        num_classes=2, name="confusion_matrix")

### Traning:

with tf.Graph().as_default():
    sess = tf.Session(config=session_conf)
    with sess.as_default():
        cnn = TextCNN(
            sequence_length=max_l,
            num_classes=len(y_train[0]),
            vocab_size=len(vocab),
            word2vec_W=W,
            word_idx_map=word_idx_map,
            user_embeddings=user_embeddings,
            embedding_size=FLAGS.embedding_dim,
            batch_size=FLAGS.batch_size,
            filter_sizes=list(map(int, FLAGS.filter_sizes.split(","))),
            num_filters=FLAGS.num_filters,
            l2_reg_lambda=FLAGS.l2_reg_lambda)

        # Define Training procedure
        global_step = tf.Variable(0, name="global_step", trainable=False)
        optimizer = tf.train.AdamOptimizer(1e-3)
        grads_and_vars = optimizer.compute_gradients(cnn.loss)
        train_op = optimizer.apply_gradients(grads_and_vars, global_step=global_step)
        saver = tf.train.Saver(tf.global_variables(), max_to_keep=FLAGS.num_checkpoints)
        sess.run(tf.global_variables_initializer())




num_classes:  2
sequence_length:  80
vocab_size:  25538
batch_size:  4096
filter_sizes:  [3, 4, 5]
num_filters:  128
embedding_size:  300
l2_loss:  Tensor("Const:0", shape=(), dtype=float32)
conv:  Tensor("conv-maxpool-3/conv:0", shape=(?, 78, 1, 128), dtype=float32)
pooled:  Tensor("conv-maxpool-3/pool:0", shape=(?, 1, 1, 128), dtype=float32)
conv:  Tensor("conv-maxpool-4/conv:0", shape=(?, 77, 1, 128), dtype=float32)
pooled:  Tensor("conv-maxpool-4/pool:0", shape=(?, 1, 1, 128), dtype=float32)
conv:  Tensor("conv-maxpool-5/conv:0", shape=(?, 76, 1, 128), dtype=float32)
pooled:  Tensor("conv-maxpool-5/pool:0", shape=(?, 1, 1, 128), dtype=float32)
h_pool_flat:  Tensor("h_pool_flat:0", shape=(?, 384), dtype=float32)
h_last:  Tensor("last_layer/h_last:0", shape=(?, 80), dtype=float32)
user_embedding_vectors:  Tensor("embedding/embedding_lookup_1/Identity:0", shape=(?, 80), dtype=float32, device=/device:CPU:0)
combined_vectors:  Tensor("user_embedding_layer/concat:0", shape=(?, 160), dtyp

In [ ]:
def train_step(x_batch, author_batch, y_batch):
    """
    A single training step
    """
    feed_dict = {
        cnn.input_x: x_batch,
        cnn.input_author: author_batch,
        cnn.input_y: y_batch,
        cnn.dropout_keep_prob: FLAGS.dropout_keep_prob
    }
    _, step, loss, accuracy = sess.run(
        [train_op, global_step, cnn.loss, cnn.accuracy],
        feed_dict)
    time_str = datetime.datetime.now().isoformat()
    return loss, accuracy

In [ ]:
def dev_step(x_batch, author_batch, y_batch):
    """
    Evaluates model on a dev set
    """
    feed_dict = {
        cnn.input_x: x_batch,
        cnn.input_author: author_batch,
        cnn.input_y: y_batch,
        cnn.dropout_keep_prob: 1.0
    }
    step, loss, conf_mat = sess.run(
        [global_step, cnn.loss, cnn.confusion_matrix],
        feed_dict)
    return loss, conf_mat


In [ ]:
def batch_iter(data, batch_size, num_epochs, shuffle=True):
    """
    Generates a batch iterator for a dataset.
    """
    data = np.array(data)
    data_size = len(data)
    num_batches_per_epoch = int((len(data)-1)/batch_size) + 1
    for epoch in range(num_epochs):
        # Shuffle the data at each epoch
        print(epoch)
        if shuffle:
            shuffle_indices = np.random.permutation(np.arange(data_size))
            shuffled_data = data[shuffle_indices]
        else:
            shuffled_data = data
        for batch_num in range(num_batches_per_epoch):
            start_index = batch_num * batch_size
            end_index = min((batch_num + 1) * batch_size, data_size)
            yield shuffled_data[start_index:end_index]


In [ ]:
def batch_iter_dev(data, batch_size):
    """
    Generates a batch iterator for a dataset.
    """
    data = np.array(data)
    data_size = len(data)
    num_batches_per_epoch = int((len(data)-1)/batch_size) + 1

    # shuffled_data = data
    ind = []
    for batch_num in range(num_batches_per_epoch):
        start_index = batch_num * batch_size
        end_index = min((batch_num + 1) * batch_size, data_size)
        ind.append((start_index, end_index))
    return ind


# Generate batches:

In [ ]:
batches = batch_iter(
    list(zip(x_train, author_train, y_train)), FLAGS.batch_size, FLAGS.num_epochs)
dev_batches = batch_iter(
    list(zip(x_dev, author_dev, y_dev)), FLAGS.batch_size, FLAGS.num_epochs)

### prints:

In [ ]:
batches

<generator object batch_iter at 0x7fdc666ba350>

In [ ]:
dev_batches

<generator object batch_iter at 0x7fdce9750430>

# Training loop, For each batch:


In [ ]:
train_loss = []
train_acc = []
best_acc = 0
for batch in batches:
    x_batch, author_batch, y_batch = zip(*batch)
    x_batch = np.asarray(x_batch)
    author_batch = np.asarray(author_batch)
    y_batch = np.asarray(y_batch)
    t_loss, t_acc = train_step(x_batch, author_batch, y_batch)
    current_step = tf.train.global_step(sess, global_step)
    train_loss.append(t_loss)
    train_acc.append(t_acc)
    if current_step % FLAGS.evaluate_every == 0:
        print(current_step)
        print("Train loss {:g}, Train acc {:g}".format(np.mean(np.asarray(train_loss)), np.mean(np.asarray(train_acc))))
        train_loss = []
        train_acc = []
        # Divide into batches
        dev_batches = batch_iter_dev(list(zip(x_dev, author_dev, y_dev)), FLAGS.batch_size)
        dev_loss = []
        ll = len(dev_batches)
        conf_mat = np.zeros((2, 2))
        for dev_batch in dev_batches:
            x_dev_batch = x_dev[dev_batch[0]:dev_batch[1]]
            author_dev_batch = author_dev[dev_batch[0]:dev_batch[1]]
            y_dev_batch = y_dev[dev_batch[0]:dev_batch[1]]
            a, b = dev_step(x_dev_batch, author_dev_batch, y_dev_batch)
            dev_loss.append(a)
            conf_mat += b
        valid_accuracy = float(conf_mat[0][0] + conf_mat[1][1]) / len(y_dev)
        print("Valid loss {:g}, Valid acc {:g}".format(np.mean(np.asarray(dev_loss)), valid_accuracy))
        print("Valid - Confusion Matrix: ")
        print(conf_mat)
        test_batches = batch_iter_dev(list(zip(x_test, author_test, y_test)), FLAGS.batch_size)
        test_loss = []
        conf_mat = np.zeros((2, 2))
        for test_batch in test_batches:
            x_test_batch = x_test[test_batch[0]:test_batch[1]]
            author_test_batch = author_test[test_batch[0]:test_batch[1]]
            y_test_batch = y_test[test_batch[0]:test_batch[1]]
            a, b = dev_step(x_test_batch, author_test_batch, y_test_batch)
            test_loss.append(a)
            conf_mat += b
        print("Test loss {:g}, Test acc {:g}".format(np.mean(np.asarray(test_loss)),
                                                     float(conf_mat[0][0] + conf_mat[1][1]) / len(y_test)))
        print("Test - Confusion Matrix: ")
        print(conf_mat)
        sys.stdout.flush()
        if best_acc < valid_accuracy:
            best_acc = valid_accuracy
            directory = "/content/drive/MyDrive/twitter_files/models"
            if not os.path.exists(directory):
                os.makedirs(directory)
            saver.save(sess, directory + '/main_balanced_users', global_step=1)


<ipython-input-312-bdab5d6a02dd>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array(data)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
100
Train loss 13.8513, Train acc 0.834768
Valid loss 17.9077, Valid acc 0.642594
Valid - Confusion Matrix: 
[[590. 211.]
 [274. 282.]]
Test loss 18.7065, Test acc 0.637703
Test - Confusion Matrix: 
[[1467.  552.]
 [ 678.  698.]]
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
200
Train loss 0.887989, Train acc 0.980397
Valid loss 18.2252, Valid acc 0.652911
Valid - Confusion Matrix: 
[[595. 206.]
 [265. 291.]]
Test loss 19.2097, Test acc 0.642415
Test - Confusion Matrix: 
[[1466.  553.]
 [ 661.  715.]]
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
300
Train loss 0.626552, Train acc 0.992309
Valid loss 17.5011, Valid acc 0.654385
Valid - Confusion Matrix: 
[[597. 204.]
 [265. 291.]]
Test loss 18.6109, Test acc 0.642121
Test - Confusion Matrix: 
[[1469.  550.]
 [ 665.  711.]]


In [ ]:
best_acc

0.6543846720707442

In [ ]:
current_step

300